export const API_BASE_URL = 'https://api.agora.cash';
export const API_ENDPOINTS = {
  TOKEN_ORDERS: (tokenId: string) => `/orders/token/${tokenId}`,
} as const;

export const TOKEN_IDS = {
  STAR_SHARD: 'd1131675cb62b65909fb45ba53b022da0bd0f34aaa71fc61770115472b186ffb',
} as const;

export const PRICE_CONSTANTS = {
  MIN_STAR_SHARD_PRICE: 2.0,
  STAR_SHARD_FLOOR_PRICE: 4.0,
  PRICE_RATIO_THRESHOLD: 0.95,
  MAX_INCREASE_PERCENT: 1000,
  MAX_DECREASE_PERCENT: 90,
  MAX_INCREASE_MULTIPLIER: 11,
  MIN_DECREASE_MULTIPLIER: 0.1,
} as const;

export const UPDATE_INTERVALS = {
  THREE_SECONDS: 3000,
  TEN_SECONDS: 10000,
  ONE_MINUTE: 60000,
  FIVE_MINUTES: 300000,
} as const;

export const UI_CONSTANTS = {
  AMOUNT_BAR_MULTIPLIER: 3,
  HIGHLIGHT_DURATION: 1000,
  ORDERBOOK_WIDTH_THRESHOLD: 500,
  ORDERBOOK_BAR_MULTIPLIER: 1.2,
} as const;

export const CHART_CONSTANTS = {
  AMOUNT_DIVISOR: 100,
  DATE_CUTOFF: '2024-09-01',
  MAX_CHART_POINTS: 168,
  TOP_HOLDERS_COUNT: 8,
  TOTAL_CHART_COLORS: 5,
} as const;

export const ORDERBOOK_CONSTANTS = {
  COLLAPSED_ORDERS_COUNT: 100,
  EXPANDED_ORDERS_COUNT: 100,
  LIQUIDITY_REWARD_THRESHOLD: 0.7,
  DEFAULT_REFERENCE_PRICE: 100,
  SPREAD_DECREMENT: 0.001,
} as const;
